int main()
{
<<<<<<< HEAD
    // int a, g, f;
    // const int c1 = 1, c2 = 2;
    // a = g = f = 42;
    // a += g -= f *= 2;
    // float y = 5.25;
    // int x = 8;
    // int z = 7;
    // char c = 'a';
    // bool tr = true;
    // x += y;
    // x -= y;
    // x *= y;
    // x /= y;
    // x %= z;
    // x <<= z;
    // x >>= z;
    // x |= z;
    // x &= z;
    // x ^= z;
    // x = x + c;
    // x = x - 8;
    // x = x * 9;
    // x = x / c;
    // x = x % 8;
    // x = x << 1;
    // x = x >> tr;
    // x = x | tr;
    // x = x & c;
    // x = x ^ 9;
    // string w = "g";
    // string ww = "dy";
    // ww = w + ww;
    // x++;
    // ++x;
    // x--;
    // --x;
    // bool b = x > 8;
    // b = x < 8;
    // b = x <= 8;
    // b = x >= 8;
    // b = x == 0;
    // b = x != 6;
    // b = x == 0 && x != 7;
    // b = x != 8 || x < 8;
    // bool flat = w == "y";
    // int u = ~x;
    // bool bc = !tr;
    // int neg = -(x + 1);
    int x = 5;
    float y = x;
    char c = x;
    int xx = y;
    int xc = c;
    bool b = x;
    int xb = b;
=======
    int a, g, f;
    const int c1 = 1, c2 = 2;
    a = g = f = 42;
    a += g -= f *= 2;
    float y = 5.25;
    int x = 8;
    int z = 7;
    char c = 'a';
    bool tr = true;
    x += y;
    x -= y;
    x *= y;
    x /= y;
    x %= z;
    x <<= z;
    x >>= z;
    x |= z;
    x &= z;
    x ^= z;
    x = x + c;
    x = x - 8;
    x = x * 9;
    x = x / c;
    x = x % 8;
    x = x << 1;
    x = x >> tr;
    x = x | tr;
    x = x & c;
    x = x ^ 9;
    string w = "g";
    x++;
    ++x;
    x--;
    --x;
    bool b = x > 8;
    b = x < 8;
    b = x <= 8;
    b = x >= 8;
    b = x == 0;
    b = x != 6;
    b = x == 0 && x != 7;
    b = x != 8 || x < 8;
    bool flat = w == "y";
    int u = ~x;
    bool bc = !tr;
    int neg = -(x + 1);
>>>>>>> c65c73a21822f070e50c0b5fc4be4b93061eba4f
}
